config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show]

  get 'welcome/index'

  ActiveAdmin.routes(self)
  
  resources :properties do
    resources :reviews, only: [:create]
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  get 'get_comunes', to: 'properties#get_comunes', as: 'get_comunes'
  get 'user_properties', to: 'properties#user_properties', as: 'user_properties'
  root 'welcome#index'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  post "get_map", to: "locations#get_map"
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    if conversation == nil
      flash[:alert] = "Faltan campos!"
      redirect_to new_conversation_path
    else
      flash[:success] = "Tu mensaje se ha enviado exitosamente!"  
      redirect_to conversation_path(conversation)
    end
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <% if  conversation.originator.avatar?%>
        <%= image_tag conversation.originator.avatar_url(:thumb), class: "media-object"%>
      <% else %>
        <%= image_tag('avatar.png', size: "64x64", class:"media-object")%>
      <% end %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <% if conversation.originator.username == current_user.username %>
        Yo <br>
      <% else %>
        <%= link_to conversation.originator.username, profile_path(conversation.originator) %> <br>
      <% end %>
      <small><b>Para: </b><%= conversation.participants.first.username  %></small><br>
      <small><b>Asunto: </b><%= conversation.subject %></small><br>
      <small><b>Fecha: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    
    
    <button type="button" class="btn btn-default btn-md pull-right">
      <%= link_to "Ver Conversación", conversation_path(conversation)  %>
    </button>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients, 'Usuarios:'%>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject , 'Asunto:' %>
      <%= f.text_field :subject, placeholder: "Escriba el asunto", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message , 'Mensaje:'%>
      <%= f.text_area :body, class: 'form-control',placeholder: "Escribe tu mensaje acá", rows: 4  %>
    </div>

    <%= f.submit "Enviar mensaje", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <% if  message.sender.avatar?%>
            <%= image_tag message.sender.avatar_url(:thumb), class: "media-object"%>
          <% else %>
            <%= image_tag('avatar.png', size: "64x64", class:"media-object")%>
          <% end %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.username%> <br>
          <small><b>Asunto: </b><%= message.subject %></small><br>
          <small><b>Fecha: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Crear Nuevo Mensaje", new_conversation_path, class: "btn btn-success" %>
  </div>
  <br>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Restaurar', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Eliminar', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Se eliminara la conversacion?'} %>
    <% end %>
  </div>
</div>


 <!-- caja con mails enviados y eliminados -->


<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

<!-- caja con conversaciones  -->

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Escribe tu mensaje aqui", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Enviar", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>