config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show]

  get 'welcome/index'

  ActiveAdmin.routes(self)
  
  resources :properties do
    resources :reviews, only: [:create]
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  get 'get_comunes', to: 'properties#get_comunes', as: 'get_comunes'
  get 'user_properties', to: 'properties#user_properties', as: 'user_properties'
  root 'welcome#index'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  post "get_map", to: "locations#get_map"
  
end

app/models/property.rb
class Property < ActiveRecord::Base
  before_save :default_wifi, :default_parking
  after_create :fill_capacity

  belongs_to :user
  belongs_to :comune
  belongs_to :city
  has_many :reviews

  validates :room, :mt2 ,:double_bed ,:single_bed ,:cabin ,:bathroom ,:description , :city_id, :address, :comune_id, presence: true



  geocoded_by :full_address
  after_validation :geocode
  mount_uploader :images, ImagesUploader

  def default_wifi
    wifi ||= false
    return
  end

  def default_parking
    parking ||= false
    return
  end

  def full_address
    [address, comune.name , city.name, 'chile' ].compact.join(', ')
  end

  def fill_capacity
    self.capacity = (double_bed*2) + (cabin*2)+ single_bed
    self.save  
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  load_and_authorize_resource except: :get_comunes
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :select_location
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @reviews = @property.reviews.reverse
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  def get_comunes
    @comunes = Comune.where("city_id = ?", params[:city_id])
    respond_to do |format|
     format.js
    end
  end



  

    
  
  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.user = current_user if user_signed_in?
    

    respond_to do |format|
      if @property.save
        current_user.owner!
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end
   

    def select_location
      @cities = City.all
      @comunes = Comune.where("city_id = ?", City.first.id)
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:room, :mt2, :double_bed, :single_bed, :cabin, :bathroom, :description, :images, :address, :latitude, :longitude, :user_id, :city_id, :comune_id, :wifi, :parking, :capacity, :type, :full_street_address, :images_cache)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container">
    <div class="row">
      <div class="col-md-6 portfolio-item">

        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>

        <div class="field">
          <%= f.label :room %><br>
          <%= f.number_field :room %>
        </div>
        <div class="field">
          <%= f.label :mt2 %><br>
          <%= f.number_field :mt2 %>
        </div>
        <div class="field">
          <%= f.label :double_bed %><br>
          <%= f.number_field :double_bed %>
        </div>
        <div class="field">
          <%= f.label :single_bed %><br>
          <%= f.number_field :single_bed %>
        </div>
        <div class="field">
          <%= f.label :cabin %><br>
          <%= f.number_field :cabin %>
        </div>
        <div class="field">
          <%= f.label :bathroom %><br>
          <%= f.number_field :bathroom %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
        
        <div class="field">
          <%= f.label :images %><br>
          <%= f.file_field :images %>
        </div>
        
        <div class="field">
          <%= f.label :wifi %><h1><span class="glyphicon glyphicon-signal"></span></h1> <br>
          <%= f.check_box :wifi %>
        </div>



        <div class="field">
          <%= f.label :parking %><br>
          <%= f.check_box :parking %>
        </div>
        

      </div>



      <div class="col-md-6 portfolio-item">
       
        <div class="field">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: 'address_map' %>
        </div>

        <div class="field">
          <%= f.select :city_id, options_for_select(@cities.collect { |city| [city.name.titleize, city.id] }), {prompt: "Select something"}, { id: 'cities_select', class: 'city_map' } %>
        </div>

        <div id="comune_map">
           <%= f.select :comune_id, options_for_select(@comunes.collect { |comune|
          [comune.name.titleize, comune.id] }), { include_blank: true }, { id: 'comunes_select', class: 'comune_map' } %>
        </div>
        
        <div style='width: 600px;'>
         <div id="multi_markers" style='width: 500px; height: 400px;'></div>
        </div>
      </div>

    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
  
<div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Propiedades
                    <small>texto secundario</small>
                </h1>
            </div>
        </div>
        
        <div class="row">
          <% @properties.each do |property| %>
            <div class="col-md-3 portfolio-item">
              <div class="panel panel-default">
               <div class="panel-body">
                <a href="#">
                  <% if property.images? %>
                    <%= image_tag(property.images, size: "700x400", class:"img-responsive") %>
                  <% else %>
                    <%= image_tag('casa.png', size: "700x400", class:"img-responsive")%>
                  <% end %>
                </a>
                <h3><a href=""><%= property.title %></a></h3>
                <p><%= truncate property.description, length: 40 %></p>
                
                <%= link_to 'Ver', property %>
              </div>  
            </div>
          </div>
      <% end %>
    </div>
  </div>
<!-- 
<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Images</th>
      <th>Room</th>
      <th>Mt2</th>
      <th>Double bed</th>
      <th>Single bed</th>
      <th>Cabin</th>
      <th>Bathroom</th>
      <th>Description</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>User</th>
      <th>Comune</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <% if property.images? %>
          <td><%= image_tag(property.images, size: "250x250") %></td>
        <% else %>
          <td><%= image_tag('casa.png', size: "250x250")  %></td>
        <% end %>
        <td><%= property.room %></td>
        <td><%= property.mt2 %></td>
        <td><%= property.double_bed %></td>
        <td><%= property.single_bed %></td>
        <td><%= property.cabin %></td>
        <td><%= property.bathroom %></td>
        <td><%= property.description %></td>
        <td><%= property.address %></td>
        <td><%= property.latitude %></td>
        <td><%= property.longitude %></td>
        <td><%= property.user %></td>
        <td><%= property.comune %></td>
        <td><%= link_to 'Show', property %></td>

        <% if can? :update, property %>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <% end %>

        <% if can? :destroy, property %>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table> -->

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @property.title %>
</p>

<p>
  <strong>Room:</strong>
  <%= @property.room %>
</p>

<p>
  <strong>Mt2:</strong>
  <%= @property.mt2 %>
</p>

<p>
  <strong>Double bed:</strong>
  <%= @property.double_bed %>
</p>

<p>
  <strong>Single bed:</strong>
  <%= @property.single_bed %>
</p>

<p>
  <strong>Cabin:</strong>
  <%= @property.cabin %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @property.bathroom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Images:</strong>
  <p>
    <%= image_tag(@property.images) if @property.images? %>
  </p>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @property.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @property.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @property.user %>
</p>

<p>
  <strong>Comune:</strong>
  <%= @property.comune %>
</p>

<div style='width: 600px;'>
   <div id="map" style='width: 500px; height: 400px;'></div>
  </div>
</div>


<% if can? :update, @property %>
  <%= link_to 'Edit', edit_property_path(@property) %> |
<% end %>
<% if can? :destroy, @property %>
  <%= link_to 'Destroy', @property, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', properties_path %>


<div>
<% if can? :create, Review %>
  <h2 class="display-4 m-t-1 m-b-1">Deja tu review</h2>
  <div class="row">
      <%= render partial: 'reviews/form' %>
  </div>
<% end %>
  
  <% if @property.reviews.any? %>
  <h2 class="display-4 m-t-1 m-b-1">Reviews (<%= @property.reviews.size %>)</h2>
  <%= render partial: 'reviews/review', collection: @reviews %>
<% end %>
  
</div>