config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show]

  get 'welcome/index'

  ActiveAdmin.routes(self)
  
  resources :properties do
    resources :reviews, only: [:create]
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  get 'get_comunes', to: 'properties#get_comunes', as: 'get_comunes'
  get 'user_properties', to: 'properties#user_properties', as: 'user_properties'
  root 'welcome#index'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  post "get_map", to: "locations#get_map"
  
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>


	    </button>
	    <a class="navbar-brand" href="/">depa.cl</a>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
	      <li><a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Busca tu lugar </a></li>

	      <% if can? :manage, ActiveAdmin::Page %>
					<li><%= link_to 'Ir a vista de administrador', admin_root_path %></li>
	      <% end %>
	      <li><%= link_to 'Buscas donde vacacionar?', properties_path %></li>
	    </ul>

	    <ul class="nav navbar-nav navbar-right">
			  <% unless user_signed_in? %>
			    <li><p class="navbar-text">Tienes una propiedad?</p></li>
			    <li><%= link_to 'Registrar', new_user_registration_path %></li>
			    <li><%= link_to 'Ingresar', new_user_session_path %></li>
			  <% else %>
				<li><%= link_to "Hello, #{current_user.name} #{current_user.lastname}", profile_path(current_user)%></li>
					
				<li role="presentation" class="active"><%= link_to mailbox_inbox_path do %> 
					<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Correo
					<span class="badge"><%= unread_messages_count %></span> 
				<% end %></li>
				

		      	<li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Opciones <b class="caret"></b></a>
			        <ul class="dropdown-menu">
								<li class="divider"></li>
							  	<li><%= link_to 'Agregar Propiedad', new_property_path %></li>
							  	<li><%= link_to 'Editar usuario', edit_user_registration_path %></li>
								<li class="divider"></li>

								<li class="divider"></li>
							
					      <li><a href="#">opciones ejemplo</a></li>

					      <li class="divider"></li>
					      
					      <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, data: { confirm: "Seguro que desea salir?" } %></li>
			        </ul>
		      </li>
		    <% end %>
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</nav>