config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show]

  get 'welcome/index'

  ActiveAdmin.routes(self)
  
  resources :properties do
    resources :reviews, only: [:create]
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :users
  get 'get_comunes', to: 'properties#get_comunes', as: 'get_comunes'
  get 'user_properties', to: 'properties#user_properties', as: 'user_properties'
  root 'welcome#index'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  post "get_map", to: "locations#get_map"
  
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(unread: true).count(:id, distinct: true)
  end
end

app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <%= link_to "Crear Nuevo Mensaje", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"><br></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Mails</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Enviados</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Eliminados</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>